### ISSUE TITLE
How to change the shebang expresseion

### ISSUE THREAD

**Issue by tangmaomao16** [yousefvand/shellman#15]
The default shebang expression is `#!/usr/bin/env bash`
But I want to change it into `#!/bin/bash`
How can I do that?

**Comment by SuperSandro2000** [comment]
You shouldn't do this as it break compability with some OS's and you can't currently as the code is shared with some other programming languages https://github.com/yousefvand/shellman/blob/d10c3ba6e233c7b700a09c52291731424a5ab642/snippets/snippets.json#L7 .

**Comment by yousefvand** [comment]
As SuperSandro2000 said usually it is not a good idea to hard-code shell engine path. Anyway a workaround would be defining your own `shebang` as a user snippet. To do so, from main menu go to:
`File -> Preferences -> User Snippets` then from opened list select `shellscript.json`. Inside this file, paste:

```
{
	"myshebang": {
		"prefix": [
			"my bash",
			"my shebang"
		],
		"body": "#!/bin/bash\n\n",
		"description": "my own shebang"
	}
}
```

You can add your snippets with a `my` prefix to group them under `my` namespace.

**Comment by tangmaomao16** [comment]
I want to use my bash script on Ubuntu1804.  But on Ubuntu1804 there's no such path as /usr/bin/env. I can't understand why use /use/bin/env bash . ------------------ 原始邮件 ------------------
发件人: "Sandro"<notifications@github.com>
发送时间: 2020年4月25日(星期六) 晚上6:09
收件人: "yousefvand/shellman"<shellman@noreply.github.com>;
抄送: "tangmaomao16"<419242057@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [yousefvand/shellman] How to change the shebang expresseion (#15)




 
You shouldn't do this as it break compability with some OS's and you can't currently as the code is shared with some other programming languages https://github.com/yousefvand/shellman/blob/d10c3ba6e233c7b700a09c52291731424a5ab642/snippets/snippets.json#L7 .
 
&mdash;

**Comment by SuperSandro2000** [comment]
``/use/bin/env`` exists in Ubuntu 18.04. you can always start the script with ``bash file.sh``.
Also here is a good explanation https://askubuntu.com/a/716281/878259

**Comment by tangmaomao16** [comment]
I checked the path again. I was wrong. I thought /usr/bin/env was a directory, and bash was in that directory. I made such mistake. Later I find that /usr/bin/env is a file.
```
$ file /usr/bin/env
/usr/bin/env: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/l, for GNU/Linux 3.2.0, BuildID[sha1]=92a80275c7d29d451b8d1971f02f7f59d971d160, stripped
```
And I will learn the meaning of /usr/bin/env. Thank you.

**Comment by tangmaomao16** [comment]
I copy the content of the wikipedia.

> env may also be used in the hashbang line of a script to allow the interpreter to be looked up via the PATH. For example, here is the code of a very simple Python script:

```
#!/usr/bin/env python3
print('Hello, World!')
```

> In this example, /usr/bin/env is the full path of the env command. The environment is not altered.

> Note that it is possible to specify the interpreter without using env, by giving the full path of the python interpreter.  A problem with that approach is that on different computer systems, the exact path may be different. By instead using env as in the example, the interpreter is searched for and located at the time the script is run (more precisely, env does a system call to execvp, which does the job of locating the interpreter and launching it). 
This makes the script more portable, but also increases the risk that the wrong interpreter is selected because it searches for a match in every directory on the executable search path. It also suffers from the same problem in that the path to the env binary may also be different on a per-machine basis. 

In conclusion, I think using /usr/bin/env bash is good for bash script shebang line. Because usually, bash only has unique version interpreter.
