### ISSUE TITLE
Import func problems

### ISSUE THREAD

**Issue by robertolabarca** [yousefvand/shellman#16]
![20200427_192838](https://user-images.githubusercontent.com/3769893/80431435-7158d680-88bf-11ea-91e0-4c6ff8d79693.gif)

**Comment by yousefvand** [comment]
Hello

It seems the bash built-in function `source` is not found. make sure you have following line at top of every file:

#!/usr/bin/env bash

and here is a sample project:

```bash
.
├── lib
│   └── some-func.sh
└── main.sh
```

![1](https://user-images.githubusercontent.com/18329462/80478661-137dca80-8963-11ea-9c27-728c05d52e5f.png)

![2](https://user-images.githubusercontent.com/18329462/80478690-1d9fc900-8963-11ea-9e81-a48dfc6e49d6.png)

To run the main file (from project path):

```
$ bash ./main.sh
# Output:
$ Calling imported function with one argument.
$ Hello robertolabarca
```

Changing `source` to `.` in import function may solve the problem too.
