### ISSUE TITLE
Use double brackets for if statements

### ISSUE THREAD

**Issue by demyxco** [yousefvand/shellman#22]
Double brackets are a bash specific feature so it would make sense to use it.

```
#!/bin/bash

if [[ condition ]]; then
     # body
elif [[ condition ]]; then
     # body
else
     # body
fi
```

**Comment by yousefvand** [comment]
You are right. When I started this extension I didn't know about `bashism`. Description should be changed to `shell scripting` snippet. There are mixed content (bash specific) which needs to be fixed.

**Comment by demyxco** [comment]
No worries. Awesome extension! I use this in my custom code-server Docker image.
