### ISSUE TITLE
Add custom Snippet

### ISSUE THREAD

**Issue by davidRFB** [yousefvand/shellman#23]
Hi ! 
Thanks for the extension of vscode. I'm wodenring if its possible to modify or create custom snippets with your extension. If its possible where i can find the json files to modify. 

Best Regards,
David

**Comment by yousefvand** [comment]
Hi David

Shellman `snippets.json` path:

- `Windows %USERPROFILE%\.vscode\extensions\remisa.shellman-{version}\snippets.json`
- `macOS ~/.vscode/extensions/remisa.shellman-{version}/snippets.json`
- `Linux ~/.vscode/extensions/remisa.shellman-{version}/snippets.json
- `Linux OSS: ~/.vscode-oss/extensions/remisa.shellman-{version}/snippets.json`

Current version is `4.7.0` so replace `{version}` in above paths.

BTW you don't need to modify that file. Create your own shell snippet and vscode activates both (shellman and yours) in shell scripts. To do so, from vscode main menu go to:

> File > Preferences > User Snippets

and from pop up menu select `shellscript.json` and add your custom snippets, save the file and your are good to go.

**Comment by davidRFB** [comment]
Thank you !!
