### ISSUE TITLE
string indexOf

### ISSUE THREAD

**Issue by cart88** [yousefvand/shellman#27]
string indexOf 
why the code template is 
temp=${v1%%"substring"*} && indexOf=`echo ${v1%%"substring"*} | echo ${#temp}`

in   sub clause
 indexOf=`echo ${v1%%"substring"*} | echo ${#temp}`

what is the meaning of this :
`echo ${v1%%"substring"*}  

thx.

**Comment by yousefvand** [comment]
The mention syntax strips the longest match of substring from the back of given string. Example:
```
#!/usr/bin/env bash

v1="Shellman-test-snippet"
echo ${v1%%"-"*}
# Output: Shellman
```
