### ISSUE TITLE
Safer syntax for cmd.failure-check and cmd.success-check

### ISSUE THREAD

**Issue by jsbrain** [yousefvand/shellman#30]
Hey,
I'm fairly new to bash scripts and this extension really helped me a ton!

But now after messing around for a while I found out about numerical and lexicographical comparison differences and now I'm wondering, if it is a good idea to use

```sh
if [[ $? != 0 ]]; then
  echo "Last command failed"
fi
```

as the `command failed` snippet or if there is a special reason to use `[[ ... ]]` instead of `(( ... ))` here?
I know this absolutely works fine when you know exactly what you're doing (what you probably always should) but for me it feels like this might lead you to - in an less concentrated moment or as a newbie (hello 👋🙂) - to change this snippet to something like

```sh
if [[ $? > 3 ]]; then
   echo "Last command failed"
fi
```

which in fact works fine for `$? => 4` but will fail for `$? => 10` as 10 has a lower lexicographical order and as in this case `[[ $? > 3 ]]` does a lexicographical comparison, not a numerical comparison, the code would not work. In fact, that's exactly what I accidentally did causing me headaches until I found out that's not the way to do it. 🤦🏻‍♂️

Anyway, then question is: Is there any special reason to use `[[ ... ]]` to compare against `$? = 0 | 1` that leads to this being the preferred solution for that matter or wouldn't it be generally safer to change the snippet to `(( $? != 0 ))`?

So maybe I'm totally wrong but to my newly acquired knowledge the suggested change would work just as fine but would also still work in case someone stupid as me fiddles around with bash and uses the shellman snippets for that matter 🙂

Happy to receive your feedback!

**Comment by yousefvand** [comment]
Hey, nice catch. Definitely this is a bug. Actually this is one of the first snippests of Shellman and at the time I didn't know about `((...))`. TBH I'm in the process of learning shell script myself. If you're intrested in sending a PR, here is
the code, [cmd.failure-check](https://github.com/yousefvand/shellman/blob/master/nsroot/command/failure-check.json#L7) and [cmd.success-check](https://github.com/yousefvand/shellman/blob/master/nsroot/command/success-check.json#L7)
