### ISSUE TITLE
request help to create another vscode extension

### ISSUE THREAD

**Issue by mh-firouzjaah** [yousefvand/shellman#35]
Hello, I'm sorry to take your time. I did not find any other way of communication such as email from you and I know that you'll answer these issues. That is why I am presenting it here. I have been looking for a while to find or build a plugin to auto-formats Django template code in V.S.Code, and I even have a syntax to create indentations when typing code, but I was unable to attach it to a good auto-format plugin to do it automatically. I ask you to make this useful plugin If you have free time.
‌Best regards.
(also there is [`django-html` ](https://marketplace.visualstudio.com/items?itemName=batisteo.vscode-django) created by `batisteo`. and appending the following code to the `language-configuration.json` file(after `"wordPattern"` part) would enable the indentations when typing code.) but thats not enough

```json
"indentationRules": {
        "increaseIndentPattern": "((\\<)(body|address|blockquote|dd|div|dl|dt|tr|tbody|thead|fieldset|form|frame|frameset|h1|h2|h3|h4|h5|h6|iframe|noframes|object|ol|p|ul|applet|center|dir|a|menu|pre|table|button|a|abbr|acronym|area|b|base|basefont|bdo|big|br|button|caption|cite|code|col|colgroup|del|dfn|em|font|head|html|i|img|input|ins|isindex|kbd|label|legend|li|link|map|meta|noscript|optgroup|option|param|q|s|samp|script|select|small|span|strike|strong|style|sub|sup|table|tbody|td|textarea|tfoot|th|thead|title|tr|tt|u|var))|(\\{\\%)\\s*(autoescape|block|blocktrans|blocktranslate|plural|comment|debug|for|empty|if|elif|else|ifchanged|ifequal|ifnotequal|from|spaceless|with|verbatim|thumbnail)",
        "decreaseIndentPattern": "((\\<\\/)(.*)*(\\>))|((\\{\\%)\\s*(empty|elif|else|end(autoescape|block|blocktrans|blocktranslate|comment|for|if|ifchanged|ifequal|ifnotequal|spaceless|with|verbatim|thumbnail)))"
    }
```

**Comment by yousefvand** [comment]
Hello
I don't have any experience with Django but there are many resources out there about making vscode extensions, BTW Shellman is not an extension and it's code snippet.
