### ISSUE TITLE
Snippets for functions and array refers to readarray command which does not exist

### ISSUE THREAD

**Issue by bcowgill** [yousefvand/shellman#43]
Your snippet for array filter expands to:

readarray -t filtered < <(for i in "${myArray[@]}" ; do echo "${i}"; done | grep 'pattern')

And other snippets make use of this command.

But there is no readarray command on Mac bash.  Is this a program that must be installed and from where?
If so you might want to put that in as a comment in the snippet.
Or a function perhaps that you have but didn't include in the snippets?
 
bash --version
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin20)
Copyright (C) 2007 Free Software Foundation, Inc.

$ readarray
bash: readarray: command not found

**Comment by yousefvand** [comment]
hey. thank you for for your comment.
This is a generic bash solution for all linux distros.
