### ISSUE TITLE
Feature request: check if is wsl, windows, mac or linux, maybe also linux distribution

### ISSUE THREAD

**Issue by leobastiani** [yousefvand/shellman#48]
Would you accept PRs?
Could you elaborate anything you would expect to see in a PR?

**Comment by Haltarys** [comment]
Do you want a snippet for each of them ?

**Comment by Haltarys** [comment]
Here are my bash functions to do this:
```zsh
is_wsl() { [[ -f "/proc/version" ]] && grep -qi WSL "/proc/version"; }
is_ubuntu() { [[ -f "/etc/os-release" ]] && [[ $(awk -F "=" '/^ID=/ {print $2}' "/etc/os-release") = "ubuntu" ]]; }
is_raspbian() { [[ -f "/etc/os-release" ]] && [[ $(awk -F "=" '/^ID=/ {print $2}' "/etc/os-release") = "raspbian" ]]; }
is_macos() { [[ "$(uname -s)" == "Darwin" ]]; }
```

It seems like this repo isn't very actively maintained. I'll try to implement that into [my own fork](https://github.com/Haltarys/shellman).

**Comment by yousefvand** [comment]
> Would you accept PRs?
> Could you elaborate anything you would expect to see in a PR?

Yes PRs are welcome.
Do one change in nsroot each time (add/edit) test it and send it to this project.
